-- ============================================================
--  Contenu de reference du site public, pour la recette.
--
--  Extrait VERBATIM de `donnees-recette.sql` (dump pg_dump de la
--  pile Supabase) : seules les lignes `content_items` sont
--  conservees, mot pour mot.
--
--  Pourquoi ne pas reutiliser le dump complet ? Parce qu'il contient
--  aussi les `members` d'origine. Les rejouer recreerait des comptes
--  avec les identifiants UUID de l'ancien `auth.users` et sans ligne
--  dans `member_credentials` : personne ne pourrait se connecter, et
--  l'echec se presenterait comme un bug de l'authentification. Les
--  comptes sont donc crees par `scripts/seed-comptes-recette.mjs`, qui
--  ecrit les deux tables coherentes.
--
--  Les autres tables du dump (`activity_log`, `leads`,
--  `whatsapp_outbox`) sont des residus de passage de la recette ; le
--  seed les purge avec --reset, il n'y a donc rien a importer.
--
--  Les donnees ne sont pas reecrites a la main : un contenu invente
--  rendrait la recette incapable de detecter une divergence de
--  format, et pourrait reintroduire sans le vouloir les incoherences
--  pays/signataire signalees dans AGENTS.md.
-- ============================================================
INSERT INTO public.content_items VALUES ('74e9c5f9-8c70-48a8-a3ed-7fe4fb6a291e', 'config', 'site', 'Configuration du site', true, 0, '{"hero": {"badge": "Agence Digitale & Éditeur Logiciel • Yaoundé & Partout dans le Monde", "subtitle": "Conception sur-mesure de plateformes e-commerce avec encaissement instantané MTN MoMo & Orange Money, activations terrain et le logiciel ARKA-PME pour piloter votre entreprise sans dépendre d''Internet.", "stat_1_val": "10-14j", "stat_2_val": "100%", "stat_3_val": "0 FCFA", "cta_primary": "Demander un devis interactif", "stat_1_label": "Délai moyen de livraison contractuel", "stat_2_label": "Fonctionnel hors-ligne pour ARKA-PME", "stat_3_label": "Frais de licence forcée ou matériel imposé", "title_line_1": "On ne livre pas un site.", "cta_secondary": "Tester ARKA-PME (30j gratuit)", "title_highlight": "On déploie votre système."}, "contact": {"phone_call": "+237 681 46 29 82", "disponibilite": "Support technique 24/7 sous astreinte • Bureaux 8h00 - 18h30", "email_contact": "ARCKATON12@gmail.com", "address_douala": "Bonanjo, Face Chambre de Commerce, Douala, Cameroun", "address_yaounde": "Quartier Bastos, Carrefour Dragages, Yaoundé, Cameroun", "whatsapp_number": "+237681462982", "whatsapp_display": "+237 681 46 29 82"}, "announcement": {"text": "Ouverture du pôle Grand Compte à Douala Bonanjo & Passerelles MTN MoMo v2.1 opérationnelles.", "badge": "DÉPLOIEMENT T3 2026", "enabled": true, "target_url": "#blog", "button_text": "Découvrir le rapport"}}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:34:40.705953+00');
INSERT INTO public.content_items VALUES ('aa953e4d-db81-499f-a827-9c3bea61739e', 'forfait', 'synergie', 'Synergie', true, 2, '{"id": "synergie", "name": "Synergie", "delai": "3 à 4 semaines", "number": "02", "tagline": "Le système digital complet le plus choisi par les PME africaines et internationales pour accélérer leur chiffre d''affaires.", "retouches": "3 rounds de retouches inclus", "recommended": true, "monthly_price": "350 000 FCFA/mois", "creation_price": "750 000 FCFA", "sorties_terrain": "9 sorties terrain / mois", "monthly_features": ["9 sorties terrain / mois & captations photos/vidéos", "2 à 3 infographies / créations par semaine", "Gestion et animation des campagnes d''acquisition", "Rapport mensuel ROI & KPIs de conversion", "Support WhatsApp dédié + accès Arckaton OS"], "creation_features": ["Identité de marque complète & charte détaillée", "Site web sur-mesure UX/UI (5 à 8 pages)", "Optimisation SEO local & mobile accéléré", "Kit réseaux sociaux & templates éditables", "Hébergement haute performance 1 an inclus", "Formation approfondie 2 heures de l''équipe"], "monthly_price_amount": 350000, "creation_price_amount": 750000}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:34:40.705953+00');
INSERT INTO public.content_items VALUES ('ba5faf79-e521-4163-983c-4750655994e5', 'forfait', 'architecture', 'Architecture', true, 3, '{"id": "architecture", "name": "Architecture", "delai": "6 à 10 semaines", "number": "03", "tagline": "L''infrastructure haut de gamme pour marques exigeantes avec e-commerce, Mobile Money et déploiement multi-canal.", "retouches": "30 jours de corrections post-lancement garantis", "recommended": false, "monthly_price": "580 000 FCFA/mois", "creation_price": "2 900 000 FCFA", "sorties_terrain": "Accompagnement terrain illimité selon plan", "monthly_features": ["Stratégie de contenu premium (3 vidéos / semaine)", "Gestion de campagnes publicitaires sponsorisées", "Optimisation continue du taux de conversion (CRO)", "Reporting hebdomadaire avec tableau de bord temps réel", "Support prioritaire 24/7 avec Chef de projet dédié"], "creation_features": ["E-commerce complet (jusqu''à 50 produits configurés)", "Paiement Mobile Money direct (MTN MoMo + Orange Money)", "Design immersif sur-mesure & animations fluides", "Système ARKA-PME connecté (stocks & ventes synchronisés)", "Hébergement cloud dédié 1 an & certificat SSL sécurisé", "Formation complète des équipes & documentations"], "monthly_price_amount": 580000, "creation_price_amount": 2900000}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:34:40.705953+00');
INSERT INTO public.content_items VALUES ('e80b047a-5724-463b-a731-fd8b1fd4340e', 'blog', 'immersion-terrain-mokolo-mimboman-captation-arka', 'Immersion Terrain : 48h au cœur des commerces de Mokolo & Mimboman avec notre équipe captation', true, 4, '{"id": "post-1", "date": "10 Septembre 2026", "slug": "immersion-terrain-mokolo-mimboman-captation-arka", "tags": ["Terrain", "Yaoundé", "Shooting 4K", "Mokolo", "Commerce Local"], "image": "https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?auto=format&fit=crop&w=1200&q=80", "title": "Immersion Terrain : 48h au cœur des commerces de Mokolo & Mimboman avec notre équipe captation", "content": "À 7h30 du matin au marché de Mokolo à Yaoundé, le flux de clients est déjà dense. Dans le cadre de notre Forfait Synergie, notre pôle terrain intervient directement sur site pour capturer l''essence authentique des produits.\n\nAccompagné d''un stabilisateur DJI RS3, de micros HF cravate et d''éclairages LED autonomes sur batterie, Boris W. et Diane B. ont orchestré 3 heures de captation continue.\n\n\"Le commerçant n''a pas 15 jours à consacrer à un studio photo. Notre méthode est claire : c''est l''agence qui descend dans la poussière du terrain pour capter la réalité et l''élever aux standards internationaux.\"\n\nRésultats livrés en 48 heures :\n- 60 visuels produits détourés et optimisés pour le web mobile\n- 4 vidéos courtes (Reels/TikTok) captant le geste artisanal\n- Intégration directe dans le catalogue ARKA-PME du client.", "excerpt": "Comment nos cadreurs et spécialistes UX transforment un étal physique en catalogue e-commerce haute définition sans interrompre l''activité du commerçant.", "category": "terrain", "featured": true, "read_time": "5 min", "field_spec": {"lieu": "Marché Mokolo & Mimboman, Yaoundé", "materiel": "Sony Alpha 7IV, DJI RS3, Kit Nanlite Pavotube, Bornes de test ARKA-PME", "date_mission": "08 Septembre 2026", "agents_mobilises": ["Boris W. (Chef Op)", "Diane B. (DA)", "Cadreur Terrain #1"], "livrables_generes": "60 photographies RAW traitées + 4 capsules vidéo 4K + 1 catalogue digital synchronisé"}, "author_name": "Boris W.", "author_role": "Directeur des Opérations & Terrain", "category_label": "Opérations Terrain"}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:34:40.705953+00');
INSERT INTO public.content_items VALUES ('1dc16f8e-ac6e-44e6-b997-7a968b5cb541', 'blog', 'etude-de-cas-maison-kotto-ecommerce-momo-orange', 'Étude de Cas : Comment Maison Kotto a quadruplé son chiffre d''affaires digital avec MTN MoMo direct', true, 5, '{"id": "post-2", "date": "06 Septembre 2026", "slug": "etude-de-cas-maison-kotto-ecommerce-momo-orange", "tags": ["E-commerce", "Mobile Money", "ROI", "Yaoundé", "Maison Kotto"], "image": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80", "title": "Étude de Cas : Comment Maison Kotto a quadruplé son chiffre d''affaires digital avec MTN MoMo direct", "content": "Avant l''intervention d''Arckaton, Maison Kotto (boutique de prêt-à-porter haut de gamme à Bastos) subissait un taux d''abandon de commande de 72% sur WhatsApp. Les clients devaient négocier, demander le numéro MoMo, envoyer une capture d''écran, attendre la vérification manuelle...\n\nGrâce au Forfait Architecture Arckaton :\n1. Déploiement d''un site web à l''esthétique épurée avec chargement ultra-rapide (<1.2s sur réseau 3G/4G local).\n2. Passerelle de paiement automatisée : le client clique, entre son numéro MTN ou Orange, valide son code PIN sur son téléphone, et la commande est confirmée en 4 secondes.\n3. Notification instantanée par SMS et impression automatique du bordereau de livraison sur l''imprimante thermique du magasin.\n\nEn 45 jours d''exploitation :\n- +337% de transactions en ligne effectives\n- Zéro litige sur les preuves de virement falsifiées\n- 12 400 000 FCFA d''encaissements sécurisés.", "excerpt": "Analyse d''une transformation digitale complète : passage d''un tunnel WhatsApp chaotique à un e-commerce sur mesure convertissant à 4.8%.", "category": "client", "featured": true, "read_time": "6 min", "author_name": "Patrice M.", "author_role": "Directeur Général Arckaton", "client_quote": {"role": "Fondatrice & Gérante", "quote": "Arckaton a résolu le cauchemar des fausses captures d''écran de transfert. Désormais, l''argent est sur notre compte avant même que le livreur ne charge le colis. C''est le jour et la nuit.", "author": "Mireille Kotto", "company": "Maison Kotto Bastos", "metrics": "+337% de conversion • 12.4M FCFA encaissés • 0 impayé"}, "category_label": "Client Satisfait & ROI"}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:34:40.705953+00');
INSERT INTO public.content_items VALUES ('fc59b466-2b93-476a-a6da-5ac6a8481f96', 'blog', 'deploiement-arka-pme-districash-nord-douala', 'De 3 heures de pointage papier à 12 minutes chrono : Déploiement ARKA-PME chez Districash Nord', true, 6, '{"id": "post-3", "date": "01 Septembre 2026", "slug": "deploiement-arka-pme-districash-nord-douala", "tags": ["ARKA-PME", "Offline-First", "Douala", "Gestion Stock", "Logistique"], "image": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80", "title": "De 3 heures de pointage papier à 12 minutes chrono : Déploiement ARKA-PME chez Districash Nord", "content": "À Douala, les délestages électriques et les coupures de fibre sous-marine peuvent paralyser une entreprise pendant plusieurs jours. Pour Districash Nord (3 hangars de stockage, 4 800 références), utiliser un logiciel Cloud classique était une source permanente d''angoisse.\n\nArckaton a installé l''architecture ARKA-PME :\n- Base de données SQLite chiffrée embarquée localement sur les ordinateurs et tablettes de caisse.\n- Fonctionnement 100% autonome sans aucune connexion Internet requise.\n- Dès que la connexion revient (même 3G via partage de connexion), les stocks se synchronisent en tâche de fond de manière invisible.\n\nLe temps de clôture de caisse quotidien est passé de 3h15 à 12 minutes précises, avec traçabilité intégrale de chaque sortie d''entrepôt.", "excerpt": "Retour d''expérience chez un grossiste en matériaux à Douala : éliminer la dépendance à Internet tout en gardant une caisse infaillible.", "category": "arka", "featured": false, "read_time": "4 min", "author_name": "Yannick K.", "author_role": "Tech Lead & Architecte SaaS", "client_quote": {"role": "Directeur Général", "quote": "Même quand la lumière coupe et qu''Internet s''arrête, mes caissiers continuent de biper les articles et d''imprimer les tickets. C''est exactement ce dont les PME d''ici ont besoin.", "author": "El Hadj Ousmane", "company": "Districash Nord", "metrics": "3h03 de gagnées chaque soir • 4 800 articles suivis en temps réel"}, "category_label": "SaaS ARKA-PME"}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:34:40.705953+00');
INSERT INTO public.content_items VALUES ('b20aa9a7-4071-4ddc-acfd-b000836ab51a', 'blog', 'coulisses-rd-architecture-resiliente-afrique-centrale', 'Coulisses R&D : Comment concevoir des architectures web résilientes face aux réalités africaines', true, 7, '{"id": "post-4", "date": "28 Août 2026", "slug": "coulisses-rd-architecture-resiliente-afrique-centrale", "tags": ["Architecture", "Performance", "Webhooks", "MoMo API", "Souveraineté"], "image": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80", "title": "Coulisses R&D : Comment concevoir des architectures web résilientes face aux réalités africaines", "content": "Trop d''agences importent des modèles occidentaux inadaptés au contexte camerounais : sites de 15 Mo bardés de scripts tiers, formulaires nécessitant une carte bancaire Visa internationale, hébergements lointains avec 350ms de latence...\n\nChez Arckaton, notre charte d''ingénierie repose sur 4 piliers stricts :\n1. Poids total de la page d''accueil bridé sous les 800 Ko (compression Brotli / WebP chirurgicale).\n2. PWA (Progressive Web App) avec mise en cache agressive des actifs vitaux.\n3. Intégration native des Webhooks MTN MoMo v2 et Orange Money avec file d''attente résiliente (RabbitMQ / BullMQ) pour ne jamais perdre un paiement en cas de micro-coupure de l''opérateur télécom.\n4. Hébergement distribué avec CDN Edge en Afrique de l''Ouest pour garantir un First Contentful Paint inférieur à 800ms.", "excerpt": "Pourquoi nous refusons les frameworks lourds et comment notre stack technique garantit une fluidité absolue même en zone à faible couverture réseau.", "category": "tech", "featured": false, "read_time": "7 min", "author_name": "Arthur N.", "author_role": "Lead Développeur Full-Stack", "category_label": "Ingénierie & Tech"}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:34:40.705953+00');
INSERT INTO public.content_items VALUES ('0632fba3-4fbf-47c5-a0f2-30a09b4e6290', 'realisation', 'kotto', 'Maison Kotto', true, 8, '{"id": "kotto", "name": "Maison Kotto", "delay": "7 semaines de déploiement", "points": ["Passerelle MTN MoMo & Orange Money sans friction avec validation instantanée", "Shooting photo studio & direction artistique packaging à Yaoundé", "Suivi régulier des stocks et synchronisation multi-boutiques"], "forfait": "Forfait Architecture", "category": "ecommerce", "subMetric": "Paniers moyens passés de 14 000 FCFA à 38 000 FCFA", "mainMetric": "+337%", "description": "Refonte complète de l''identité de marque, boutique e-commerce avec encaissement Mobile Money automatisé (MTN/Orange) et 3 capsules vidéo par semaine.", "categoryLabel": "Cosmétique & Luxe Africain", "mainMetricLabel": "De conversion e-commerce en 6 mois"}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:34:40.705953+00');
INSERT INTO public.content_items VALUES ('c08b105b-cbbc-449e-9afa-02ce22dcb3d2', 'realisation', 'districash', 'Districash Nord', true, 9, '{"id": "districash", "name": "Districash Nord", "delay": "Déployé en 10 jours", "points": ["Temps d''inventaire complet réduit de 3 heures à 12 minutes", "Fonctionnement 100% garanti hors connexion en cas de coupure", "Clôture comptable automatique par caissier et par point de vente"], "forfait": "ARKA-PME SaaS", "category": "saas", "subMetric": "12 000 références suivies en temps réel", "mainMetric": "12,8M FCFA", "description": "Déploiement du logiciel ARKA-PME sur 4 dépôts régionaux pour synchroniser les stocks, éliminer les pertes et automatiser la facturation hors-ligne.", "categoryLabel": "Grande Distribution & Négoce", "mainMetricLabel": "Flux financier consolidé sans écart de caisse"}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:34:40.705953+00');
INSERT INTO public.content_items VALUES ('20e31754-214b-4ac2-902f-42b32bcdbeab', 'realisation', 'rapha', 'Clinique El Rapha', true, 10, '{"id": "rapha", "name": "Clinique El Rapha", "delay": "3 semaines de production", "points": ["Taux de rebond réduit à 24% sur mobile avec design ergonomique", "Prise de rendez-vous directe synchronisée avec le secrétariat", "Capsules pédagogiques vidéo animées par les médecins"], "forfait": "Forfait Synergie", "category": "sante", "subMetric": "1ère position sur les requêtes spécialisées à Yaoundé", "mainMetric": "4.9 / 5", "description": "Site vitrine médical haut de gamme, prise de rendez-vous en ligne, SEO local Yaoundé et 9 sorties terrain pour valoriser les spécialistes et équipements.", "categoryLabel": "Santé & Établissement Médical", "mainMetricLabel": "Note moyenne Google & Avis Patients"}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:34:40.705953+00');
INSERT INTO public.content_items VALUES ('ade8ed3f-677e-4374-9b1e-392784439f90', 'temoignage', 'temoignage-kotto', 'Mireille Kotto', true, 11, '{"id": "temoignage-kotto", "role": "Fondatrice & Gérante", "text": "Arckaton a résolu le cauchemar des fausses captures d''écran de transfert. Désormais, l''argent est sur notre compte avant même que le livreur ne charge le colis. C''est le jour et la nuit.", "author": "Mireille Kotto", "company": "Maison Kotto, Bastos", "metrics": "+337% de conversion • 12.4M FCFA encaissés • 0 impayé"}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:34:40.705953+00');
INSERT INTO public.content_items VALUES ('30ae7aab-dbf9-47ce-9e09-4dba5b9c211e', 'temoignage', 'temoignage-districash', 'Direction Générale', true, 12, '{"id": "temoignage-districash", "role": "Directeur des Opérations", "text": "Nos gérants ne perdent plus aucune vente lors des coupures de courant. L''inventaire est passé de 3 heures à 12 minutes chrono. ARKA-PME a sauvé notre rentabilité.", "author": "Direction Générale", "company": "Districash Nord, Douala", "metrics": "Inventaire en 12 min • 12 000 références • Mode hors-ligne"}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:34:40.705953+00');
INSERT INTO public.content_items VALUES ('5d9afe2c-b2e7-413c-a83a-20ea41cab351', 'temoignage', 'temoignage-rapha', 'Direction Médicale', true, 13, '{"id": "temoignage-rapha", "role": "Praticien Hospitalier", "text": "La fiche Google a déjà généré une hausse visible des appels pour les consultations. Les rendez-vous en ligne ont modernisé l''accueil de notre secrétariat.", "author": "Direction Médicale", "company": "Clinique El Rapha, Yaoundé", "metrics": "4.9/5 Google • +38 appels/semaine • 1ère position locales"}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:34:40.705953+00');
INSERT INTO public.content_items VALUES ('e0d128f5-6890-4a3b-84cd-1419156da788', 'forfait', 'initiation', 'Initiation', true, 0, '{"id": "initiation", "name": "Initiation", "delai": "10 à 15 jours ouvrés", "number": "01", "tagline": "L''essentiel solide pour démarrer une présence digitale crédible et générer des premiers contacts qualifiés.", "retouches": "2 rounds de retouches inclus", "recommended": false, "monthly_price": "160 000 FCFA/mois", "creation_price": "380 000 FCFA", "sorties_terrain": "6 sorties terrain / mois", "monthly_features": ["6 sorties terrain / mois avec captation", "Maintenance technique & sécurité", "Support WhatsApp réactif 6j/7", "Mises à jour de contenus mensuelles"], "creation_features": ["Logo & charte graphique simplifiée", "Mini-site vitrine responsive (3 à 5 pages)", "Kit graphique de lancement (6 visuels pro)", "Hébergement & nom de domaine inclus 1 an", "Formation prise en main 2 heures", "Intégration WhatsApp & formulaires"], "monthly_price_amount": 160000, "creation_price_amount": 380000}', '2026-10-01 00:34:40.705953+00', '2026-10-01 00:41:46.938+00');

